# Generated by Django 3.1.5 on 2021-03-06 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=20)),
                ('state', models.CharField(choices=[('TX', 'Texas'), ('OTHERS', 'Out of Texas')], max_length=20)),
                ('zipcode', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pricing_Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallons', models.IntegerField(default=0)),
                ('delivery_date',models.DateField(auto_now=False,auto_now_add=False)),
                ('delivery_address', models.CharField(default='', max_length=100)),
                ('s_price', models.DecimalField(max_digits=10,decimal_places=2)),#suggested Price
                ('t_price', models.DecimalField(max_digits=10,decimal_places=2)),#total price
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserProfile')),#keep lowercase F it has to do with app name in urls
            ],# was thinking about adding a foriegn key (user probably) need to ask jafar about it
        ),
    ]
