# Generated by Django 3.1.5 on 2021-03-11 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FuelRatePredSys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing_Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallons', models.IntegerField(default=0)),
                ('delivery_date', models.DateField()),
                ('delivery_address', models.CharField(default='', max_length=100)),
                ('s_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('t_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FuelRatePredSys.userprofile')),
            ],
        ),
    ]
