# Generated by Django 3.1.7 on 2021-03-31 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FuelRatePredSys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricing_module',
            old_name='gallons',
            new_name='gallons_requested',
        ),
        migrations.RenameField(
            model_name='pricing_module',
            old_name='s_price',
            new_name='suggested_price',
        ),
        migrations.RenameField(
            model_name='pricing_module',
            old_name='t_price',
            new_name='total_price',
        ),
    ]
