# Generated by Django 3.1.7 on 2021-03-31 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FuelRatePredSys', '0002_auto_20210331_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing_module',
            name='userprofile',
        ),
        migrations.AddField(
            model_name='pricing_module',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pricing_module',
            name='delivery_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pricing_module',
            name='gallons_requested',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pricing_module',
            name='suggested_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pricing_module',
            name='total_price',
            field=models.FloatField(),
        ),
    ]
